salloc: Granted job allocation 4015341
srun: Job step created
cudaRuntimeGetVersion() failed with error #38
WARNING: log_file config option not found - no log file is being saved
2016-12-09 10:19:00 [ERROR] ValueError: Unable to find supported images in /tmp/zim021.1042/tmpKxm4aO
Traceback (most recent call last):
File "/data/zim021/digits-proj/DIGITS/digits/tools/create_generic_db.py", line 478, in <module>
args['stage']
File "/data/zim021/digits-proj/DIGITS/digits/tools/create_generic_db.py", line 443, in create_generic_db
force_same_shape)
File "/data/zim021/digits-proj/DIGITS/digits/tools/create_generic_db.py", line 296, in create_db
entry_ids = extension.itemize_entries(stage)
File "/data/zim021/digits-proj/DIGITS/digits/extensions/data/imageProcessing/data.py", line 115, in itemize_entries
feature_image_list = self.make_image_list(self.feature_folder)
File "/data/zim021/digits-proj/DIGITS/digits/extensions/data/imageProcessing/data.py", line 153, in make_image_list
raise ValueError("Unable to find supported images in %s" % folder)
ValueError: Unable to find supported images in /tmp/zim021.1042/tmpKxm4aO
srun: error: g018: task 0: Exited with exit code 1
salloc: Relinquishing job allocation 4015341
salloc: Job allocation 4015341 has been revoked.
